#!/usr/bin/env php
<?php
/**
 *  Conversion settings files from one format to another
 *
 * PHP version 7
 *
 * @category None
 * @package  None
 * @author   me <me@somewhere.out>
 * @license  https://opensource.org/licenses/MIT MIT
 * @link     none
 */
namespace Convert;

use function \Converter\convert;
use function \Converter\Error\error;

require_once __DIR__ . '/vendor/autoload.php';

$options = getopt("i:o:");
if (!isset($options['i']) || !isset($options['o'])) {
    error('missing parameters. usage convert -i input.file -o output.file');
}

convert($options['i'], $options['o']);
exit(0);
